select a.linkname
,'<a href="#" onclick="alertWin('''+a.linkname+'score'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=score&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull(((s.[fvalue_host]+s.[fvalue_instance]-1)/25),-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),100-convert(int,isnull(s.[fvalue_host]+s.[fvalue_instance],101)))+'</span></span></div></a>' as [score]

--,'<a href="#" onclick="alertWin('''+a.linkname+'cpu_user'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=cpu_user&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([cpu_user_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(cpu_user_value,-1)))+'%</span></span></div></a>' as [cpu_user]
--,'<a href="#" onclick="alertWin('''+a.linkname+'cpu_system'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=cpu_system&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([cpu_system_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(cpu_system_value,-1)))+'%</span></span></div></a>' as [cpu_system]
,'<a href="#" onclick="alertWin('''+a.linkname+'cpu_idle'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=cpu_idle&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([cpu_idle_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),100-convert(int,isnull(cpu_idle_value,101)))+'%</span></span></div></a>' as [cpu_idle]
--,'<a href="#" onclick="alertWin('''+a.linkname+'load_1min'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=load_1min&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([load_1min_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(load_1min_value,-1)))+'%</span></span></div></a>' as [load_1min]
--,'<a href="#" onclick="alertWin('''+a.linkname+'load_5min'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=load_5min&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([load_5min_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(load_5min_value,-1)))+'%</span></span></div></a>' as [load_5min]
,'<a href="#" onclick="alertWin('''+a.linkname+'mem_memfree_percent'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=mem_memfree_percent&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([mem_memfree_percent_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,100-isnull(mem_memfree_percent_value,101)))+'%</span></span></div></a>' as [mem_memfree_percent]
,'<a href="#" onclick="alertWin('''+a.linkname+'mem_swapfree_percent'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=mem_swapfree_percent&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([mem_swapfree_percent_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,100-isnull(mem_swapfree_percent_value,101)))+'%</span></span></div></a>' as [mem_swapfree_percent]
,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_util'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_util&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_util_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_util_value,-1)))+'%</span></span></div></a>' as [disk_io_util]

,'<a href="#" onclick="alertWin('''+a.linkname+'cpu_iowait'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=cpu_iowait&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([cpu_iowait_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(cpu_iowait_value,-1)))+'</span></span></div></a>' as [cpu_iowait]
--,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_await'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_await&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_await_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_await_value,-1)))+'</span></span></div></a>' as [disk_io_await]
--,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_avgrq_sz'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_avgrq_sz&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_avgrq_sz_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_avgrq_sz_value,-1)))+'</span></span></div></a>' as [disk_io_avgrq_sz]
,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_avgqu_sz'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_avgqu_sz&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_avgqu_sz_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_avgqu_sz_value,-1)))+'</span></span></div></a>' as [disk_io_avgqu_sz]
--,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_ios_in_progress'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_ios_in_progress&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_ios_in_progress_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_ios_in_progress_value,-1)))+'%</span></span></div></a>' as [disk_io_ios_in_progress]
--,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_msec_read'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_msec_read&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_msec_read_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_msec_read_value,-1)))+'</span></span></div></a>' as [disk_io_msec_read]
--,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_msec_total'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_msec_total&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_msec_total_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_msec_total_value,-1)))+'</span></span></div></a>' as [disk_io_msec_total]
--,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_msec_weighted_total'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_msec_weighted_total&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_msec_weighted_total_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_msec_weighted_total_value,-1)))+'%</span></span></div></a>' as [disk_io_msec_weighted_total]
--,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_msec_write'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_msec_write&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_msec_write_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_msec_write_value,-1)))+'</span></span></div></a>' as [disk_io_msec_write]
--,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_read_bytes'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_read_bytes&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_read_bytes_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_read_bytes_value,-1)))+'</span></span></div></a>' as [disk_io_read_bytes]
--,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_read_merged'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_read_merged&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_read_merged_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_read_merged_value,-1)))+'%</span></span></div></a>' as [disk_io_read_merged]
,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_read_requests'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_read_requests&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_read_requests_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_read_requests_value,-1)))+'</span></span></div></a>' as [disk_io_read_requests]
,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_write_requests'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_write_requests&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_write_requests_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_write_requests_value,-1)))+'</span></span></div></a>' as [disk_io_write_requests]
--,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_read_sectors'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_read_sectors&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_read_sectors_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_read_sectors_value,-1)))+'%</span></span></div></a>' as [disk_io_read_sectors]
--,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_write_bytes'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_write_bytes&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_write_bytes_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_write_bytes_value,-1)))+'</span></span></div></a>' as [disk_io_write_bytes]
--,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_write_merged'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_write_merged&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_write_merged_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_write_merged_value,-1)))+'%</span></span></div></a>' as [disk_io_write_merged]
--,'<a href="#" onclick="alertWin('''+a.linkname+'disk_io_write_sectors'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=disk_io_write_sectors&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([disk_io_write_sectors_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(disk_io_write_sectors_value,-1)))+'%</span></span></div></a>' as [disk_io_write_sectors]
--,'<a href="#" onclick="alertWin('''+a.linkname+'net_if_total_bytes'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=net_if_total_bytes&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([net_if_total_bytes_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(net_if_total_bytes_value/1024/1024,-1)))+'</span></span></div></a>' as [net_if_total_bytes]
--,'<a href="#" onclick="alertWin('''+a.linkname+'net_if_total_errors'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=net_if_total_errors&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([net_if_total_errors_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(net_if_total_errors_value/1024/1024,-1)))+'</span></span></div></a>' as [net_if_total_errors]
--,'<a href="#" onclick="alertWin('''+a.linkname+'TcpExt_TCPAbortOnTimeout'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=TcpExt_TCPAbortOnTimeout&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([TcpExt_TCPAbortOnTimeout_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(TcpExt_TCPAbortOnTimeout_value,-1)))+'</span></span></div></a>' as [TcpExt_TCPAbortOnTimeout]
--,'<a href="#" onclick="alertWin('''+a.linkname+'ss_closed'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=ss_closed&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([ss_closed_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(ss_closed_value,-1)))+'</span></span></div></a>' as [ss_closed]
--,'<a href="#" onclick="alertWin('''+a.linkname+'ss_timewait'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=ss_timewait&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([ss_timewait_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,isnull(ss_timewait_value,-1)))+'</span></span></div></a>' as [ss_timewait]



,'<a href="#" onclick="alertWin('''+a.linkname+'Threads_running'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Threads_running&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Threads_running_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Threads_running_value))+'</span></span></div></a>' as [Threads_running]
,'<a href="#" onclick="alertWin('''+a.linkname+'Threads_connected'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Threads_connected&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Threads_connected_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Threads_connected_value))+'</span></span></div></a>' as [Threads_connected]
--,'<a href="#" onclick="alertWin('''+a.linkname+'Slow_launch_threads'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Slow_launch_threads&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Slow_launch_threads_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Slow_launch_threads_value))+'</span></span></div></a>' as [Slow_launch_threads]
--,'<a href="#" onclick="alertWin('''+a.linkname+'Innodb_row_lock_current_waits'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Innodb_row_lock_current_waits&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Innodb_row_lock_current_waits_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Innodb_row_lock_current_waits_value))+'</span></span></div></a>' as [Innodb_row_lock_current_waits]
--,'<a href="#" onclick="alertWin('''+a.linkname+'Innodb_row_lock_waits'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Innodb_row_lock_waits&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Innodb_row_lock_waits_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),Innodb_row_lock_waits_value)+'</span></span></div></a>' as [Innodb_row_lock_waits]
,'<a href="#" onclick="alertWin('''+a.linkname+'Queries'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Queries&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Queries_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Queries_value))+'</span></span></div></a>' as [Queries]
--,'<a href="#" onclick="alertWin('''+a.linkname+'Questions'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Questions&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Questions_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Questions_value))+'</span></span></div></a>' as [Questions]
,'<a href="#" onclick="alertWin('''+a.linkname+'Innodb_rows_read'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Innodb_rows_read&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Innodb_rows_read_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Innodb_rows_read_value))+'</span></span></div></a>' as [Innodb_rows_read]
,'<a href="#" onclick="alertWin('''+a.linkname+'Innodb_rows_inserted'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Innodb_rows_inserted&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Innodb_rows_inserted_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Innodb_rows_inserted_value))+'/'+convert(varchar(50),convert(int,Innodb_rows_updated_value))+'/'+convert(varchar(50),convert(int,Innodb_rows_deleted_value))+'</span></span></div></a>' as [Innodb_rows_inserted]
--,'<a href="#" onclick="alertWin('''+a.linkname+'Innodb_rows_deleted'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Innodb_rows_deleted&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Innodb_rows_deleted_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Innodb_rows_deleted_value))+'</span></span></div></a>' as [Innodb_rows_deleted]
--,'<a href="#" onclick="alertWin('''+a.linkname+'Innodb_rows_updated'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Innodb_rows_updated&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Innodb_rows_updated_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Innodb_rows_updated_value))+'</span></span></div></a>' as [Innodb_rows_updated]
--,'<a href="#" onclick="alertWin('''+a.linkname+'Com_select'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Com_select&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Com_select_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Com_select_value))+'</span></span></div></a>' as [Com_select]
--,'<a href="#" onclick="alertWin('''+a.linkname+'Com_insert'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Com_insert&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Com_insert_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Com_insert_value))+'</span></span></div></a>' as [Com_insert]
--,'<a href="#" onclick="alertWin('''+a.linkname+'Com_delete'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Com_delete&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Com_delete_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Com_delete_value))+'</span></span></div></a>' as [Com_delete]
--,'<a href="#" onclick="alertWin('''+a.linkname+'Com_update'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Com_update&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Com_update_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Com_update_value))+'</span></span></div></a>' as [Com_update]
--,'<a href="#" onclick="alertWin('''+a.linkname+'Com_begin'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Com_begin&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Com_begin_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Com_begin_value))+'</span></span></div></a>' as [Com_begin]
--,'<a href="#" onclick="alertWin('''+a.linkname+'Com_commit'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Com_commit&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Com_commit_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Com_commit_value))+'</span></span></div></a>' as [Com_commit]
,'<a href="#" onclick="alertWin('''+a.linkname+'Com_rollback'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Com_rollback&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Com_rollback_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Com_rollback_value))+'</span></span></div></a>' as [Com_rollback]
,'<a href="#" onclick="alertWin('''+a.linkname+'Bytes_received'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Bytes_received&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Bytes_received_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Bytes_received_value/1024))+'</span></span></div></a>' as [Bytes_received]
,'<a href="#" onclick="alertWin('''+a.linkname+'Bytes_sent'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Bytes_sent&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Bytes_sent_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Bytes_sent_value/1024))+'</span></span></div></a>' as [Bytes_sent]

,'<a href="#" onclick="alertWin('''+a.linkname+'Table_locks_waited'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Table_locks_waited&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Table_locks_waited_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),Table_locks_waited_value)+'</span></span></div></a>' as [Table_locks_waited]
,'<a href="#" onclick="alertWin('''+a.linkname+'Slow_queries'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Slow_queries&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Slow_queries_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),Slow_queries_value)+'</span></span></div></a>' as [Slow_queries]
,'<a href="#" onclick="alertWin('''+a.linkname+'Innodb_row_lock_time_avg'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=Innodb_row_lock_time_avg&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor([Innodb_row_lock_time_avg_weight]))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,Innodb_row_lock_time_avg_value))+'</span></span></div></a>' as [Innodb_row_lock_time_avg]


,'<a href="#" onclick="alertWin('''+a.linkname+'diskfreepercent'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=diskfreepercent&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([diskfreepercent_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),100-convert(int,isnull(diskfreepercent_value,101)))+'%</span></span></div></a>' as [diskfreepercent]
,'<a href="#" onclick="alertWin('''+a.linkname+'homefreepercent'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=homefreepercent&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([homefreepercent_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),100-convert(int,isnull(homefreepercent_value,101)))+'%</span></span></div></a>' as [homefreepercent]
--,'<a href="#" onclick="alertWin('''+a.linkname+'df_statistics_used_percent'',''?report_action=v&report_ptname=danvxye9zpjk4o8rw5uf20m7sc&fdpara__1='+a.linkname+'&fdpara__2=df_statistics_used_percent&authkey=dba_test6293zwj'',780,560);"><div class="progress" style="margin:0 8px;"><span class="f_'+convert(varchar(50),floor(isnull([df_statistics_used_percent_weight],-1)))+'" style="width: 100%;"><span>'+convert(varchar(50),convert(int,100-isnull(df_statistics_used_percent_value,-1)))+'%</span></span></div></a>' as [df_statistics_used_percent]


from 
[dbo].my_instance a
join dbo.faclon_counter_score s on a.instanceid=s.instanceid
left join (
  select 
  [linkname]
,sum(case when [fkey]='Threads_running' then fvalue else 0.00 end) as Threads_running_value,sum(case when [fkey]='Threads_running' then fweight else 0.0 end) as Threads_running_weight 
,sum(case when [fkey]='Threads_connected' then fvalue else 0.00 end) as Threads_connected_value,sum(case when [fkey]='Threads_connected' then fweight else 0.0 end) as Threads_connected_weight 
,sum(case when [fkey]='Table_locks_waited' then fvalue else 0.00 end) as Table_locks_waited_value,sum(case when [fkey]='Table_locks_waited' then fweight else 0.0 end) as Table_locks_waited_weight 
,sum(case when [fkey]='Slow_queries' then fvalue else 0.00 end) as Slow_queries_value,sum(case when [fkey]='Slow_queries' then fweight else 0.0 end) as Slow_queries_weight 
,sum(case when [fkey]='Slow_launch_threads' then fvalue else 0.00 end) as Slow_launch_threads_value,sum(case when [fkey]='Slow_launch_threads' then fweight else 0.0 end) as Slow_launch_threads_weight 
,sum(case when [fkey]='Innodb_row_lock_current_waits' then fvalue else 0.00 end) as Innodb_row_lock_current_waits_value,sum(case when [fkey]='Innodb_row_lock_current_waits' then fweight else 0.0 end) as Innodb_row_lock_current_waits_weight 
,sum(case when [fkey]='Innodb_row_lock_time_avg' then fvalue else 0.00 end) as Innodb_row_lock_time_avg_value,sum(case when [fkey]='Innodb_row_lock_time_avg' then fweight else 0.0 end) as Innodb_row_lock_time_avg_weight 
,sum(case when [fkey]='Innodb_row_lock_waits' then fvalue else 0.00 end) as Innodb_row_lock_waits_value,sum(case when [fkey]='Innodb_row_lock_waits' then fweight else 0.0 end) as Innodb_row_lock_waits_weight 
,sum(case when [fkey]='Innodb_rows_deleted' then fvalue else 0.00 end) as Innodb_rows_deleted_value,sum(case when [fkey]='Innodb_rows_deleted' then fweight else 0.0 end) as Innodb_rows_deleted_weight 
,sum(case when [fkey]='Innodb_rows_inserted' then fvalue else 0.00 end) as Innodb_rows_inserted_value,sum(case when [fkey]='Innodb_rows_inserted' then fweight else 0.0 end) as Innodb_rows_inserted_weight 
,sum(case when [fkey]='Innodb_rows_read' then fvalue else 0.00 end) as Innodb_rows_read_value,sum(case when [fkey]='Innodb_rows_read' then fweight else 0.0 end) as Innodb_rows_read_weight 
,sum(case when [fkey]='Innodb_rows_updated' then fvalue else 0.00 end) as Innodb_rows_updated_value,sum(case when [fkey]='Innodb_rows_updated' then fweight else 0.0 end) as Innodb_rows_updated_weight 
,sum(case when [fkey]='Queries' then fvalue else 0.00 end) as Queries_value,sum(case when [fkey]='Queries' then fweight else 0.0 end) as Queries_weight 
,sum(case when [fkey]='Questions' then fvalue else 0.00 end) as Questions_value,sum(case when [fkey]='Questions' then fweight else 0.0 end) as Questions_weight 
,sum(case when [fkey]='Slave_IO_Running' then fvalue else 0.00 end) as Slave_IO_Running_value,sum(case when [fkey]='Slave_IO_Running' then fweight else 0.0 end) as Slave_IO_Running_weight 
,sum(case when [fkey]='Com_select' then fvalue else 0.00 end) as Com_select_value,sum(case when [fkey]='Com_select' then fweight else 0.0 end) as Com_select_weight 
,sum(case when [fkey]='Com_update' then fvalue else 0.00 end) as Com_update_value,sum(case when [fkey]='Com_update' then fweight else 0.0 end) as Com_update_weight 
,sum(case when [fkey]='Com_insert' then fvalue else 0.00 end) as Com_insert_value,sum(case when [fkey]='Com_insert' then fweight else 0.0 end) as Com_insert_weight 
,sum(case when [fkey]='Com_commit' then fvalue else 0.00 end) as Com_commit_value,sum(case when [fkey]='Com_commit' then fweight else 0.0 end) as Com_commit_weight 
,sum(case when [fkey]='Com_delete' then fvalue else 0.00 end) as Com_delete_value,sum(case when [fkey]='Com_delete' then fweight else 0.0 end) as Com_delete_weight 
,sum(case when [fkey]='Com_begin' then fvalue else 0.00 end) as Com_begin_value,sum(case when [fkey]='Com_begin' then fweight else 0.0 end) as Com_begin_weight 
,sum(case when [fkey]='Com_rollback' then fvalue else 0.00 end) as Com_rollback_value,sum(case when [fkey]='Com_rollback' then fweight else 0.0 end) as Com_rollback_weight 
,sum(case when [fkey]='Bytes_received' then fvalue else 0.00 end) as Bytes_received_value,sum(case when [fkey]='Bytes_received' then fweight else 0.0 end) as Bytes_received_weight 
,sum(case when [fkey]='Bytes_sent' then fvalue else 0.00 end) as Bytes_sent_value,sum(case when [fkey]='Bytes_sent' then fweight else 0.0 end) as Bytes_sent_weight 
  from [dbo].[faclon_counter_mysql]
  group by [linkname]
  ) b on a.faclon_instance=b.linkname
 left join (
 SELECT [linkname]
  ,sum(case when [fkey]='cpu_user' then fvalue else 0.00 end) as cpu_user_value,sum(case when [fkey]='cpu_user' then fweight else 0.0 end) as cpu_user_weight 
,sum(case when [fkey]='cpu_system' then fvalue else 0.00 end) as cpu_system_value,sum(case when [fkey]='cpu_system' then fweight else 0.0 end) as cpu_system_weight 
,sum(case when [fkey]='cpu_iowait' then fvalue else 0.00 end) as cpu_iowait_value,sum(case when [fkey]='cpu_iowait' then fweight else 0.0 end) as cpu_iowait_weight 
,sum(case when [fkey]='cpu_idle' then fvalue else 0.00 end) as cpu_idle_value,sum(case when [fkey]='cpu_idle' then fweight else 0.0 end) as cpu_idle_weight 
,sum(case when [fkey]='TcpExt_TCPAbortOnTimeout' then fvalue else 0.00 end) as TcpExt_TCPAbortOnTimeout_value,sum(case when [fkey]='TcpExt_TCPAbortOnTimeout' then fweight else 0.0 end) as TcpExt_TCPAbortOnTimeout_weight 
,sum(case when [fkey]='diskfreepercent' then fvalue else 0.00 end) as diskfreepercent_value,sum(case when [fkey]='diskfreepercent' then fweight else 0.0 end) as diskfreepercent_weight 
,sum(case when [fkey]='homefreepercent' then fvalue else 0.00 end) as homefreepercent_value,sum(case when [fkey]='homefreepercent' then fweight else 0.0 end) as homefreepercent_weight 
,sum(case when [fkey]='df_statistics_used_percent' then fvalue else 0.00 end) as df_statistics_used_percent_value,sum(case when [fkey]='df_statistics_used_percent' then fweight else 0.0 end) as df_statistics_used_percent_weight 
,sum(case when [fkey]='disk_io_avgqu_sz' then fvalue else 0.00 end) as disk_io_avgqu_sz_value,sum(case when [fkey]='disk_io_avgqu_sz' then fweight else 0.0 end) as disk_io_avgqu_sz_weight 
,sum(case when [fkey]='disk_io_avgrq_sz' then fvalue else 0.00 end) as disk_io_avgrq_sz_value,sum(case when [fkey]='disk_io_avgrq_sz' then fweight else 0.0 end) as disk_io_avgrq_sz_weight 
,sum(case when [fkey]='disk_io_await' then fvalue else 0.00 end) as disk_io_await_value,sum(case when [fkey]='disk_io_await' then fweight else 0.0 end) as disk_io_await_weight 
,sum(case when [fkey]='disk_io_ios_in_progress' then fvalue else 0.00 end) as disk_io_ios_in_progress_value,sum(case when [fkey]='disk_io_ios_in_progress' then fweight else 0.0 end) as disk_io_ios_in_progress_weight 
,sum(case when [fkey]='disk_io_msec_read' then fvalue else 0.00 end) as disk_io_msec_read_value,sum(case when [fkey]='disk_io_msec_read' then fweight else 0.0 end) as disk_io_msec_read_weight 
,sum(case when [fkey]='disk_io_msec_total' then fvalue else 0.00 end) as disk_io_msec_total_value,sum(case when [fkey]='disk_io_msec_total' then fweight else 0.0 end) as disk_io_msec_total_weight 
,sum(case when [fkey]='disk_io_msec_weighted_total' then fvalue else 0.00 end) as disk_io_msec_weighted_total_value,sum(case when [fkey]='disk_io_msec_weighted_total' then fweight else 0.0 end) as disk_io_msec_weighted_total_weight 
,sum(case when [fkey]='disk_io_msec_write' then fvalue else 0.00 end) as disk_io_msec_write_value,sum(case when [fkey]='disk_io_msec_write' then fweight else 0.0 end) as disk_io_msec_write_weight 
,sum(case when [fkey]='disk_io_read_bytes' then fvalue else 0.00 end) as disk_io_read_bytes_value,sum(case when [fkey]='disk_io_read_bytes' then fweight else 0.0 end) as disk_io_read_bytes_weight 
,sum(case when [fkey]='disk_io_read_merged' then fvalue else 0.00 end) as disk_io_read_merged_value,sum(case when [fkey]='disk_io_read_merged' then fweight else 0.0 end) as disk_io_read_merged_weight 
,sum(case when [fkey]='disk_io_read_requests' then fvalue else 0.00 end) as disk_io_read_requests_value,sum(case when [fkey]='disk_io_read_requests' then fweight else 0.0 end) as disk_io_read_requests_weight 
,sum(case when [fkey]='disk_io_read_sectors' then fvalue else 0.00 end) as disk_io_read_sectors_value,sum(case when [fkey]='disk_io_read_sectors' then fweight else 0.0 end) as disk_io_read_sectors_weight 
,sum(case when [fkey]='disk_io_util' then fvalue else 0.00 end) as disk_io_util_value,sum(case when [fkey]='disk_io_util' then fweight else 0.0 end) as disk_io_util_weight 
,sum(case when [fkey]='disk_io_write_bytes' then fvalue else 0.00 end) as disk_io_write_bytes_value,sum(case when [fkey]='disk_io_write_bytes' then fweight else 0.0 end) as disk_io_write_bytes_weight 
,sum(case when [fkey]='disk_io_write_merged' then fvalue else 0.00 end) as disk_io_write_merged_value,sum(case when [fkey]='disk_io_write_merged' then fweight else 0.0 end) as disk_io_write_merged_weight 
,sum(case when [fkey]='disk_io_write_requests' then fvalue else 0.00 end) as disk_io_write_requests_value,sum(case when [fkey]='disk_io_write_requests' then fweight else 0.0 end) as disk_io_write_requests_weight 
,sum(case when [fkey]='disk_io_write_sectors' then fvalue else 0.00 end) as disk_io_write_sectors_value,sum(case when [fkey]='disk_io_write_sectors' then fweight else 0.0 end) as disk_io_write_sectors_weight 
,sum(case when [fkey]='load_1min' then fvalue else 0.00 end) as load_1min_value,sum(case when [fkey]='load_1min' then fweight else 0.0 end) as load_1min_weight 
,sum(case when [fkey]='load_5min' then fvalue else 0.00 end) as load_5min_value,sum(case when [fkey]='load_5min' then fweight else 0.0 end) as load_5min_weight 
,sum(case when [fkey]='mem_memfree_percent' then fvalue else 0.00 end) as mem_memfree_percent_value,sum(case when [fkey]='mem_memfree_percent' then fweight else 0.0 end) as mem_memfree_percent_weight 
,sum(case when [fkey]='mem_swapfree_percent' then fvalue else 0.00 end) as mem_swapfree_percent_value,sum(case when [fkey]='mem_swapfree_percent' then fweight else 0.0 end) as mem_swapfree_percent_weight 
,sum(case when [fkey]='net_if_total_bytes' then fvalue else 0.00 end) as net_if_total_bytes_value,sum(case when [fkey]='net_if_total_bytes' then fweight else 0.0 end) as net_if_total_bytes_weight 
,sum(case when [fkey]='net_if_total_errors' then fvalue else 0.00 end) as net_if_total_errors_value,sum(case when [fkey]='net_if_total_errors' then fweight else 0.0 end) as net_if_total_errors_weight 
,sum(case when [fkey]='ss_closed' then fvalue else 0.00 end) as ss_closed_value,sum(case when [fkey]='ss_closed' then fweight else 0.0 end) as ss_closed_weight 
,sum(case when [fkey]='ss_timewait' then fvalue else 0.00 end) as ss_timewait_value,sum(case when [fkey]='ss_timewait' then fweight else 0.0 end) as ss_timewait_weight 
  FROM [dbo].[faclon_counter]
  group by linkname) 
  c on  a.faclon_host=c.linkname 
  where a.isdashbord>0 
  order by a.isdashbord desc
